ANTHILL_TYPE =        'anthill';
BRICK_TYPE =          'brick';
TREE_TYPE =           'tree';
BIG_TUBE_TYPE =       'bigTube';
BIG_BUSH_TYPE =       'bigBush';
SMALL_BUSH_TYPE =     'smallBush';
BIG_CLOUD_TYPE =      'bigCloud';
SMALL_CLOUD_TYPE =    'smallCloud';
TUBE_TYPE =           'tube';
QUESTION_BLOCK_TYPE = 'questionBlock';
QUBE_TYPE =           'qube';
FLAG_TYPE =           'flag';
BACKGROUND_COLOR =    '#5c94fc';

var mainMusic = document.getElementById("mainTheme");
mainMusic.autoplay = true;
mainMusic.load();

var arrayOfEnemiesPosition =
    [
        {showed: false, x: 700,  y: GROUND_LINE},
        {showed: false, x: 1000, y: GROUND_LINE},
        {showed: false, x: 1370, y: GROUND_LINE},
        {showed: false, x: 1410, y: GROUND_LINE},
        {showed: false, x: 2600, y: 117},
        {showed: false, x: 2650, y: 117},
        {showed: false, x: 3000, y: GROUND_LINE},
        {showed: false, x: 3100, y: GROUND_LINE},
        {showed: false, x: 3800, y: GROUND_LINE},
        {showed: false, x: 3850, y: GROUND_LINE},
        {showed: false, x: 4000, y: GROUND_LINE},
        {showed: false, x: 5500, y: GROUND_LINE},
        {showed: false, x: 5550, y: GROUND_LINE},
    ];
    var arrayOfObjects =
[
    {type: ANTHILL_TYPE,        x: 19,   y: 12},
    {type: TREE_TYPE,           x: 5,    y: 12},
    {type: TUBE_TYPE,           x: 28,   y: 12},
    {type: BIG_BUSH_TYPE,       x: 9,    y: 12},
    {type: SMALL_BUSH_TYPE,     x: 36,   y: 12},
    {type: BIG_BUSH_TYPE,       x: 42,   y: 12},
    {type: BIG_CLOUD_TYPE,      x: 5,    y: 4},
    {type: BIG_CLOUD_TYPE,      x: 32,   y: 2},
    {type: BIG_CLOUD_TYPE,      x: 46,   y: 5},
    {type: SMALL_CLOUD_TYPE,    x: 24,   y: 3},
    {type: BRICK_TYPE,          x: 20,   y: 9},
    {type: BRICK_TYPE,          x: 22,   y: 9},
    {type: BRICK_TYPE,          x: 24,   y: 9},
    {type: QUESTION_BLOCK_TYPE, x: 16,   y: 9},
    {type: QUESTION_BLOCK_TYPE, x: 21,   y: 9},
    {type: QUESTION_BLOCK_TYPE, x: 23,   y: 9},
    {type: QUESTION_BLOCK_TYPE, x: 22,   y: 5},
    {type: BIG_TUBE_TYPE,       x: 38,   y: 12},
    {type: BIG_TUBE_TYPE,       x: 46,   y: 12},
    {type: ANTHILL_TYPE,        x: 50,   y: 12},
    {type: TUBE_TYPE,           x: 56,   y: 12},
    {type: SMALL_CLOUD_TYPE,    x: 60,   y: 3},
    {type: BIG_BUSH_TYPE,       x: 59,   y: 12},
    {type: SMALL_BUSH_TYPE,     x: 68,   y: 12},
    {type: BRICK_TYPE,          x: 74,   y: 9},
    {type: QUESTION_BLOCK_TYPE, x: 75,   y: 9},
    {type: BRICK_TYPE,          x: 76,   y: 9},
    {type: SMALL_CLOUD_TYPE,    x: 71,   y: 5},
    {type: BRICK_TYPE,          x: 77,   y: 5},
    {type: BRICK_TYPE,          x: 78,   y: 5},
    {type: BRICK_TYPE,          x: 79,   y: 5},
    {type: BRICK_TYPE,          x: 80,   y: 5},
    {type: BRICK_TYPE,          x: 81,   y: 5},
    {type: BIG_CLOUD_TYPE,      x: 82,   y: 2},
    {type: BRICK_TYPE,          x: 82,   y: 5},
    {type: BRICK_TYPE,          x: 83,   y: 5},
    {type: BRICK_TYPE,          x: 84,   y: 5},
    {type: BRICK_TYPE,          x: 85,   y: 5},
    {type: BRICK_TYPE,          x: 86,   y: 5},
    {type: BIG_BUSH_TYPE,       x: 88,   y: 12},
    {type: BRICK_TYPE,          x: 90,   y: 5},
    {type: BRICK_TYPE,          x: 91,   y: 5},
    {type: BRICK_TYPE,          x: 92,   y: 5},
    {type: QUESTION_BLOCK_TYPE, x: 93,   y: 5},
    {type: BRICK_TYPE,          x: 93,   y: 9},
    {type: ANTHILL_TYPE,        x: 97,   y: 12},
    {type: BRICK_TYPE,          x: 100,  y: 9},
    {type: BRICK_TYPE,          x: 101,  y: 9},
    {type: BIG_CLOUD_TYPE,      x: 103,  y: 5},
    {type: QUESTION_BLOCK_TYPE, x: 106,  y: 9},
    {type: QUESTION_BLOCK_TYPE, x: 109,  y: 9},
    {type: QUESTION_BLOCK_TYPE, x: 112,  y: 9},
    {type: QUESTION_BLOCK_TYPE, x: 109,  y: 5},
    {type: BIG_BUSH_TYPE,       x: 108,  y: 12},
    {type: ANTHILL_TYPE,        x: 112,  y: 12},
    {type: BRICK_TYPE,          x: 118,  y: 9},
    {type: SMALL_CLOUD_TYPE,    x: 115,  y: 3},
    {type: BRICK_TYPE,          x: 121,  y: 5},
    {type: BRICK_TYPE,          x: 122,  y: 5},
    {type: BRICK_TYPE,          x: 123,  y: 5},
    {type: BIG_CLOUD_TYPE,      x: 125,  y: 4},
    {type: BRICK_TYPE,          x: 128,  y: 5},
    {type: QUESTION_BLOCK_TYPE, x: 129,  y: 5},
    {type: QUESTION_BLOCK_TYPE, x: 130,  y: 5},
    {type: BRICK_TYPE,          x: 131,  y: 5},
    {type: BRICK_TYPE,          x: 129,  y: 9},
    {type: BRICK_TYPE,          x: 130,  y: 9},
    {type: BIG_CLOUD_TYPE,      x: 135,  y: 3},
    {type: SMALL_BUSH_TYPE,     x: 138,  y: 12},
    {type: QUBE_TYPE,           x: 134,  y: 12},
    {type: QUBE_TYPE,           x: 135,  y: 12},
    {type: QUBE_TYPE,           x: 136,  y: 12},
    {type: QUBE_TYPE,           x: 137,  y: 12},
    {type: QUBE_TYPE,           x: 135,  y: 11},
    {type: QUBE_TYPE,           x: 136,  y: 11},
    {type: QUBE_TYPE,           x: 137,  y: 11},
    {type: QUBE_TYPE,           x: 136,  y: 10},
    {type: QUBE_TYPE,           x: 137,  y: 10},
    {type: QUBE_TYPE,           x: 137,  y: 9},
    {type: QUBE_TYPE,           x: 140,  y: 9},
    {type: QUBE_TYPE,           x: 140,  y: 10},
    {type: QUBE_TYPE,           x: 141,  y: 10},
    {type: QUBE_TYPE,           x: 140,  y: 11},
    {type: QUBE_TYPE,           x: 141,  y: 11},
    {type: QUBE_TYPE,           x: 142,  y: 11},
    {type: QUBE_TYPE,           x: 140,  y: 12},
    {type: QUBE_TYPE,           x: 141,  y: 12},
    {type: QUBE_TYPE,           x: 142,  y: 12},
    {type: QUBE_TYPE,           x: 143,  y: 12},
    {type: ANTHILL_TYPE,        x: 145,  y: 12},
    {type: QUBE_TYPE,           x: 148,  y: 12},
    {type: QUBE_TYPE,           x: 149,  y: 12},
    {type: QUBE_TYPE,           x: 150,  y: 12},
    {type: QUBE_TYPE,           x: 151,  y: 12},
    {type: QUBE_TYPE,           x: 152,  y: 12},
    {type: QUBE_TYPE,           x: 149,  y: 11},
    {type: QUBE_TYPE,           x: 150,  y: 11},
    {type: QUBE_TYPE,           x: 151,  y: 11},
    {type: QUBE_TYPE,           x: 152,  y: 11},
    {type: QUBE_TYPE,           x: 150,  y: 10},
    {type: QUBE_TYPE,           x: 151,  y: 10},
    {type: QUBE_TYPE,           x: 152,  y: 10},
    {type: QUBE_TYPE,           x: 151,  y: 9},
    {type: QUBE_TYPE,           x: 152,  y: 9},
    {type: SMALL_CLOUD_TYPE,    x: 153,  y: 4},
    {type: QUBE_TYPE,           x: 155,  y: 9},
    {type: QUBE_TYPE,           x: 155,  y: 10},
    {type: QUBE_TYPE,           x: 156,  y: 10},
    {type: QUBE_TYPE,           x: 155,  y: 11},
    {type: QUBE_TYPE,           x: 156,  y: 11},
    {type: QUBE_TYPE,           x: 157,  y: 11},
    {type: QUBE_TYPE,           x: 155,  y: 12},
    {type: QUBE_TYPE,           x: 156,  y: 12},
    {type: QUBE_TYPE,           x: 157,  y: 12},
    {type: QUBE_TYPE,           x: 158,  y: 12},
    {type: SMALL_BUSH_TYPE,     x: 159,  y: 12},
    {type: ANTHILL_TYPE,        x: 161,  y: 12},
    {type: SMALL_CLOUD_TYPE,    x: 164,  y: 2},
    {type: TUBE_TYPE,           x: 164,  y: 12},
    {type: SMALL_BUSH_TYPE,     x: 169,  y: 12},
    {type: BRICK_TYPE,          x: 169,  y: 9},
    {type: BRICK_TYPE,          x: 170,  y: 9},
    {type: QUESTION_BLOCK_TYPE, x: 171,  y: 9},
    {type: BRICK_TYPE,          x: 172,  y: 9},
    {type: BIG_CLOUD_TYPE,      x: 173,  y: 4},
    {type: TUBE_TYPE,           x: 180,  y: 12},
    {type: BIG_CLOUD_TYPE,      x: 183,  y: 4},
    {type: QUBE_TYPE,           x: 182,  y: 12},
    {type: QUBE_TYPE,           x: 183,  y: 12},
    {type: QUBE_TYPE,           x: 184,  y: 12},
    {type: QUBE_TYPE,           x: 185,  y: 12},
    {type: QUBE_TYPE,           x: 186,  y: 12},
    {type: QUBE_TYPE,           x: 187,  y: 12},
    {type: QUBE_TYPE,           x: 188,  y: 12},
    {type: QUBE_TYPE,           x: 189,  y: 12},
    {type: QUBE_TYPE,           x: 190,  y: 12},
    {type: QUBE_TYPE,           x: 183,  y: 11},
    {type: QUBE_TYPE,           x: 184,  y: 11},
    {type: QUBE_TYPE,           x: 185,  y: 11},
    {type: QUBE_TYPE,           x: 186,  y: 11},
    {type: QUBE_TYPE,           x: 187,  y: 11},
    {type: QUBE_TYPE,           x: 188,  y: 11},
    {type: QUBE_TYPE,           x: 189,  y: 11},
    {type: QUBE_TYPE,           x: 190,  y: 11},
    {type: QUBE_TYPE,           x: 184,  y: 10},
    {type: QUBE_TYPE,           x: 185,  y: 10},
    {type: QUBE_TYPE,           x: 186,  y: 10},
    {type: QUBE_TYPE,           x: 187,  y: 10},
    {type: QUBE_TYPE,           x: 188,  y: 10},
    {type: QUBE_TYPE,           x: 189,  y: 10},
    {type: QUBE_TYPE,           x: 190,  y: 10},
    {type: QUBE_TYPE,           x: 185,  y: 9},
    {type: QUBE_TYPE,           x: 186,  y: 9},
    {type: QUBE_TYPE,           x: 187,  y: 9},
    {type: QUBE_TYPE,           x: 188,  y: 9},
    {type: QUBE_TYPE,           x: 189,  y: 9},
    {type: QUBE_TYPE,           x: 190,  y: 9},
    {type: QUBE_TYPE,           x: 186,  y: 8},
    {type: QUBE_TYPE,           x: 187,  y: 8},
    {type: QUBE_TYPE,           x: 188,  y: 8},
    {type: QUBE_TYPE,           x: 189,  y: 8},
    {type: QUBE_TYPE,           x: 190,  y: 8},
    {type: QUBE_TYPE,           x: 187,  y: 7},
    {type: QUBE_TYPE,           x: 188,  y: 7},
    {type: QUBE_TYPE,           x: 189,  y: 7},
    {type: QUBE_TYPE,           x: 190,  y: 7},
    {type: QUBE_TYPE,           x: 188,  y: 6},
    {type: QUBE_TYPE,           x: 189,  y: 6},
    {type: QUBE_TYPE,           x: 190,  y: 6},
    {type: QUBE_TYPE,           x: 189,  y: 5},
    {type: QUBE_TYPE,           x: 190,  y: 5},
    {type: ANTHILL_TYPE,        x: 193,  y: 12},
    {type: QUBE_TYPE,           x: 195,  y: 12},
    {type: SMALL_CLOUD_TYPE,    x: 205,  y: 3},
    {type: BIG_CLOUD_TYPE,      x: 215,  y: 2},
    {type: FLAG_TYPE,           x: 195,  y: 2}
];